language: node_js
script: npm run build:prod
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  repo: rodolphenivelet.github.io
  local-dir: dist
  on:
    branch: master
