language: node_js
branches:
  only:
    - master
install:
  - npm config set @fortawesome:registry https://npm.fontawesome.com/$FONTAWESOME_TOKEN
  - npm install
script: npm run build:prod
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  repo: rodolphenivelet.github.io
  local-dir: dist
  on:
    branch: master
